# Form implementation generated from reading ui file 'D:\Documents\code\Python\Tdlt\c3\pythonProject1\ui\Câu 126\Cau126.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 352)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 531, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_height = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_height.setObjectName("line_height")
        self.gridLayout.addWidget(self.line_height, 5, 1, 1, 1)
        self.line_weight = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_weight.setObjectName("line_weight")
        self.gridLayout.addWidget(self.line_weight, 3, 1, 1, 1)
        self.bmi_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.bmi_label.setObjectName("bmi_label")
        self.gridLayout.addWidget(self.bmi_label, 6, 1, 1, 1)
        self.comment_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.comment_label.setObjectName("comment_label")
        self.gridLayout.addWidget(self.comment_label, 7, 1, 1, 1)
        self.caculatebutton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.caculatebutton.setObjectName("caculatebutton")
        self.gridLayout.addWidget(self.caculatebutton, 8, 1, 1, 1)
        self.closebutton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.closebutton.setObjectName("closebutton")
        self.gridLayout.addWidget(self.closebutton, 8, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.tittle_BMI = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.tittle_BMI.setStyleSheet("background-color: yellow")
        self.tittle_BMI.setObjectName("tittle_BMI")
        self.gridLayout.addWidget(self.tittle_BMI, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.closebutton.clicked.connect(MainWindow.close) # type: ignore
        self.caculatebutton.clicked.connect(self.tinh_bmi)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bmi_label.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.comment_label.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.caculatebutton.setText(_translate("MainWindow", "Caculate"))
        self.closebutton.setText(_translate("MainWindow", "Close"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Weight:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Height:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">BMI:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Comment:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "kg/m2"))
        self.label_9.setText(_translate("MainWindow", "(CM)"))
        self.label_10.setText(_translate("MainWindow", "(Kg)"))
        self.tittle_BMI.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">BMI Application</span></p></body></html>"))

    def tinh_bmi (self):
        try:
            bmi = float(self.line_weight.text())/((float(self.line_height.text())/100)**2)
            if bmi < 16:
                self.comment_label.setText("Severe Thinness")
            elif bmi <= 17:
                self.comment_label.setText("Moderate Thinness")
            elif bmi <= 18.5:
                self.comment_label.setText("Mild Thinness")
            elif bmi <= 25:
                self.comment_label.setText("Normal")
            elif bmi <= 30:
                self.comment_label.setText("Overweight")
            elif bmi <= 35:
                self.comment_label.setText("Obese Class I")
            elif bmi <= 40:
                self.comment_label.setText("Obese Class II")
            else:
                self.comment_label.setText("Obese Class III")
            self.bmi_label.setText(f"{bmi:.2f}")
        except ValueError:
            self.comment_label.setText("Vui lòng nhập số hợp lệ!")
        self.comment_label.setStyleSheet("color: red")
        self.bmi_label.setStyleSheet("color: blue")

import sys
from PyQt6.QtWidgets import QApplication, QDialog

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

