# Form implementation generated from reading ui file 'D:\Documents\code\Python\Tdlt\c3\pythonProject1\ui\Câu 133\Cau133.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from turtledemo.paint import changecolor

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 240)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 211, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.redbutton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.redbutton.setObjectName("redbutton")
        self.verticalLayout.addWidget(self.redbutton)
        self.greenbutton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.greenbutton.setObjectName("greenbutton")
        self.verticalLayout.addWidget(self.greenbutton)
        self.bluebutton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.bluebutton.setObjectName("bluebutton")
        self.verticalLayout.addWidget(self.bluebutton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.redbutton.clicked.connect(lambda: self.change_color(MainWindow, "red")) # type: ignore
        self.greenbutton.clicked.connect(lambda: self.change_color(MainWindow, "green")) # type: ignore
        self.bluebutton.clicked.connect(lambda: self.change_color(MainWindow, "blue")) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.redbutton.setText(_translate("MainWindow", "red"))
        self.greenbutton.setText(_translate("MainWindow", "green"))
        self.bluebutton.setText(_translate("MainWindow", "blue"))

    def change_color(self, MainWindow, color):
        MainWindow.setStyleSheet(f"background-color: {color}")


import sys
from PyQt6.QtWidgets import QApplication, QDialog

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())