# Form implementation generated from reading ui file 'D:\Documents\code\Python\Tdlt\c3\pythonProject1\ui\Cau118.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, uic
from PyQt6.QtGui import QDesktopServices
from PyQt6.QtCore import QUrl


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(586, 301)
        self.exit_button = QtWidgets.QPushButton(parent=Dialog)
        self.exit_button.setGeometry(QtCore.QRect(410, 240, 111, 28))
        self.exit_button.setObjectName("exit_button")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 240, 111, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 240, 111, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(60, 40, 201, 51))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 110, 381, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(self.open_link) # type: ignore
        self.exit_button.clicked.connect(self.show_exit_confirmation) # type: ignore
        self.pushButton_3.clicked.connect(lambda: self.show_rename(Dialog))
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exit_button.setText(_translate("Dialog", "exit"))
        self.pushButton_2.setText(_translate("Dialog", "Visit Blog"))
        self.pushButton_3.setText(_translate("Dialog", "Send name"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Your name: </span></p></body></html>"))

    def show_exit_confirmation (self):
        self.exit_dialog = uic.loadUi("exit_confirmation_cau119.ui")
        self.exit_dialog.yesbutton.clicked.connect(self.confirm_exit)
        self.exit_dialog.show()

    def show_rename (self, Dialog):
        self.rename_dialog = QDialog()
        uic.loadUi("second_window.ui", self.rename_dialog)
    #kết nối nút chuyển màu với hàm chuyển màu tương ứng
        self.rename_dialog.redbutton.clicked.connect(lambda: self.change_color_red(Dialog))
        self.rename_dialog.yellowbutton.clicked.connect(lambda: self.change_color_yellow(Dialog))
    #kết nối từ lineEdit của thẻ rename_dialog đến lineEdit của cửa sổ chính
        self.rename_dialog.lineEdit.textChanged.connect(self.lineEdit.setText)

        self.rename_dialog.show()

    def confirm_exit (self):
        # self.exit_dialog.close()
        QtWidgets.QApplication.quit()

    def open_link (self):
        url = "https://tranduythanh.com/"
        QDesktopServices.openUrl(QUrl(url))

    def change_color_red(self, Dialog):
        Dialog.setStyleSheet("background-color: red")

    def change_color_yellow(self, Dialog):
        Dialog.setStyleSheet("background-color: yellow")


import sys
from PyQt6.QtWidgets import QApplication, QDialog

if __name__ == "__main__":
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())