# Form implementation generated from reading ui file 'D:\Documents\code\Python\Tdlt\c3\pythonProject1\ui\Câu 131\Cau131.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, uic
from PyQt6.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 353)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 411, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.submitbutton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.submitbutton.setObjectName("submitbutton")
        self.gridLayout.addWidget(self.submitbutton, 8, 2, 1, 1)
        self.smart_contract = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.smart_contract.setObjectName("smart_contract")
        self.gridLayout.addWidget(self.smart_contract, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.machine_learning = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.machine_learning.setObjectName("machine_learning")
        self.gridLayout.addWidget(self.machine_learning, 5, 2, 1, 1)
        self.Full_name = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.Full_name.setObjectName("Full_name")
        self.gridLayout.addWidget(self.Full_name, 1, 2, 1, 1)
        self.deep_learning = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.deep_learning.setObjectName("deep_learning")
        self.gridLayout.addWidget(self.deep_learning, 6, 2, 1, 1)
        self.email = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setStyleSheet("background-color: yellow")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.submitbutton.clicked.connect(self.show_courses)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submitbutton.setText(_translate("MainWindow", "Submit"))
        self.smart_contract.setText(_translate("MainWindow", "Smart Contract"))
        self.label_4.setText(_translate("MainWindow", "Email:"))
        self.machine_learning.setText(_translate("MainWindow", "Machine Learning"))
        self.deep_learning.setText(_translate("MainWindow", "Deep learning"))
        self.label_3.setText(_translate("MainWindow", "Full name:"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-style:italic; color:#00aaff;\">Courses Registration</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Courses Selection:</span></p></body></html>"))

    def show_courses (self):
        self.show_courses = QtWidgets.QMainWindow()
        uic.loadUi("Selected_courses.ui", self.show_courses)

        self.show_courses.name_label.setText(self.Full_name.text())
        self.show_courses.mail_label.setText(self.email.text())
        text_courses = ""
        if self.machine_learning.isChecked():
            text_courses += "machine learning, "
        if self.deep_learning.isChecked():
            text_courses += "deep learning, "
        if self.smart_contract.isChecked():
            text_courses += "smart contract, "
        self.show_courses.courses.setText(text_courses)
        self.show_courses.show()

import sys
from PyQt6.QtWidgets import QApplication, QDialog

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
